# 넘파이(Numpy)
- 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
- 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝들 수많은 분야에서 기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="800"/>

In [2]:
import numpy as np

In [4]:
arr = np.ndarray([1, 2, 3])
print(arr)

[[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
  [1.69119873e-306 1.24611673e-306 1.05699581e-307]]]


In [6]:
# 하나의 타입으로만 정의할 수 있다.
arr2 = np.array([1, 2, 3])
print(arr2)
print(arr2)

[1 2 3]
[1 2 3]


In [7]:
# 넘파이의 타입 강제 승격
# 여러 타입을 하나로 묶을 수 있는 방법은 문자열 밖에 없어서
arr3 = np.array([1, 2, True, "asd", 15.8])
print(arr3)

['1' '2' 'True' 'asd' '15.8']


## ndarray의 인덱싱

In [13]:
arr3 = np.array([i for i in range(10)])

print(arr3[1])
print(type(arr3[1]))
print(type(1))

1
<class 'numpy.int32'>
<class 'int'>


# ndarray의 슬라이싱

In [20]:
print(arr3)
print(arr3[2:5])
print(arr3[::2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 2 4 6 8]


# shape
- numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
- arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [23]:
print(arr3)
print(arr3.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [24]:
arr4 = np.array([[2]])
print(arr4.shape)

(1, 1)


In [27]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5)
print(arr5.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [28]:
arr6 = np.array([[[1, 2, 3], [4, 5, 6]]])
print(arr6)
print(arr6.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [29]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])

print(arr7)
print(arr7.shape)

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [34]:
# 몇 차원인지 알려줌
arr7.ndim

3

In [35]:
# 데이터의 개수
arr7.size

24

In [42]:
print(arr7[1][0][2])
print(arr7[0][2][3])

for i in range(2):
    for j in range(3):
        for k in range(4):
            print(arr7[i][j][k])

300
120
10
20
30
40
50
60
70
80
90
100
110
120
100
200
300
400
500
600
700
800
900
1000
1100
1200
