# 넘파이(Numpy)
- 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
- 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝들 수많은 분야에서 기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="800"/>

In [3]:
import numpy as np

In [4]:
arr = np.ndarray([1, 2, 3])
print(arr)

[[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
  [1.69119873e-306 1.24611673e-306 1.05699581e-307]]]


In [6]:
# 하나의 타입으로만 정의할 수 있다.
arr2 = np.array([1, 2, 3])
print(arr2)
print(arr2)

[1 2 3]
[1 2 3]


In [7]:
# 넘파이의 타입 강제 승격
# 여러 타입을 하나로 묶을 수 있는 방법은 문자열 밖에 없어서
arr3 = np.array([1, 2, True, "asd", 15.8])
print(arr3)

['1' '2' 'True' 'asd' '15.8']


## ndarray의 인덱싱

In [13]:
arr3 = np.array([i for i in range(10)])

print(arr3[1])
print(type(arr3[1]))
print(type(1))

1
<class 'numpy.int32'>
<class 'int'>


# ndarray의 슬라이싱

In [20]:
print(arr3)
print(arr3[2:5])
print(arr3[::2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 2 4 6 8]


# shape
- numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
- arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [23]:
print(arr3)
print(arr3.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [24]:
arr4 = np.array([[2]])
print(arr4.shape)

(1, 1)


In [27]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5)
print(arr5.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [28]:
arr6 = np.array([[[1, 2, 3], [4, 5, 6]]])
print(arr6)
print(arr6.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [4]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])

print(arr7)
print(arr7.shape)

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [5]:
# 몇 차원인지 알려줌
arr7.ndim

3

In [6]:
# 데이터의 개수
arr7.size

24

In [7]:
print(arr7[1][0][2])
print(arr7[0][2][3])

300
120


## np.arange()
- 반복을 돌면서 넘파이에 값을 넣어줌

In [11]:
print(np.arange(10))
print(np.arange(1, 10, 2))
print(np.arange(5, 10))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[5 6 7 8 9]


In [15]:
# u: Unsigned (부호를 없애는 타입)
arr1 = np.arange(10, dtype = np.uint8)
print(type(arr1[6]))

<class 'numpy.uint8'>


## 넘파이의 자료형
- int: 부호가 있는 정수(8, 16, 32, 64)
- uint: 부호가 없는 정수(8, 16, 32, 64)
- float: 실수(16, 32, 64, 128)
- complex: x 복소수(64, 128, 256) - 잘 안씀
- bool: 불리언(8)
- string_: x 문자열(8) - 잘 안씀
- object: 오브젝트(64)

## astype(타입)
- 기존의 배열을 복사하고 타입을 변경하고 싶을 때

In [25]:
arr2 = np.arange(10)
arr3 = arr2.astype(np.int8)
print(arr3.dtype)

int8


## np.reshape()
- ndarray의 형태와 차원을 바꾸기 위해서 사용하는 메서드

In [37]:
arr3 = np.arange(12)
print(arr3.shape)

print(arr3.reshape(3, 4), end="\n\n")
print(arr3.reshape(6, 2), end="\n\n")
print(arr3.reshape(2, 2, 3), end="\n\n")
print(arr3.reshape(2, 2, 1, 3), end="\n\n")

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]]



In [40]:
arr4 = np.arange(24).reshape(2, 6, 2)
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

## np.ones(), np.zeros()
- ndarray의 초기값을 0 or 1로 설정하기 위한 메서드
- 초기화할 때 float형으로 생성이 됨

In [42]:
arr5 = np.ones(8)
arr5

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
arr6 = np.zeros(8)
print(arr6)
arr6 = np.zeros(64, dtype=np.int64)
print(arr6)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [51]:
print(arr6.reshape(4, 16))
print(arr6.reshape(4, 4, 4))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


## np.random()
- rand: 0 ~ 1 사이의 균일 분포
- randn: 정규분포
- randint: 균일 분포 정규 난수
- <img src="https://thebook.io/img/080263/218.jpg" />

In [52]:
np.random.randn(5)

array([-1.2273208 ,  0.35764406,  0.23102533, -0.6137471 ,  0.06334981])

In [167]:
np.random.randint(5)

4

In [168]:
np.random.randint(0, 100, (2, 3))

array([[ 5, 32, 91],
       [91, 57, 28]])

## seed()
- 난수를 예측가능하도록 만들며, 실행할 때마다 동일한 난수를 발생시켜,
  코드의 재현성, 특정 알고리즘의 결과를 재현하게 만든다. 또한 해당 알고리즘의 결과의 오유를 추적하기 위해 사용한다.

In [169]:
np.random.seed(4885)
np.random.randint(10, size=(2, 5))

array([[9, 1, 0, 3, 4],
       [8, 7, 4, 7, 6]])

In [174]:
np.random.seed(4885)
np.random.rand(10)

array([0.21350835, 0.56504926, 0.7597468 , 0.05666448, 0.6753598 ,
       0.36138766, 0.01299493, 0.04721084, 0.26603997, 0.8042786 ])

## unique()
- ndarray의 중복값을 제거해주는 함수

In [175]:
np.unique([11, 11, 11, 12, 13, 14, 15])

array([11, 12, 13, 14, 15])

## shape 변경

## ravel(), np.ravel()
- 다차원 배열을 1차원으로 변경하는 메서드

In [176]:
arr7 = np.arange(24).reshape(2,3,4)
arr7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [177]:
arr7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [178]:
# C: 행 반향
arr7.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [179]:
# F: 열 방향(axis(축) = -1)
# axis 1: y축
# axis 0: x축
arr7.ravel(order='F')

array([ 0, 12,  4, 16,  8, 20,  1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10,
       22,  3, 15,  7, 19, 11, 23])

## np.flatten()
- copy를 생성하고 원본 배열을 변경하지 않는 복사본을 반환한다.
- 차원 수에 상관없지 평단화가 가능해서 많이 사용된다.

In [182]:
arr7 = np.arange(24).reshape(2, 3, 4)
print(arr7)
print(arr7.flatten())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [184]:
# -1: 차원 유추
arr8 = np.arange(120).reshape(2, -1, 10)
arr8

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

## 차원 확장
- np.expand_dims()
- axis로 지정된 축을 확장시키는 메서드

In [188]:
arr8 = np.arange(10)

arr9 = np.expand_dims(arr8, axis=1)
print(arr9)

arr9 = np.expand_dims(arr8, axis=0)
print(arr9)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


## 차원 축소
- squeeze(), np.squeeze()

In [190]:
print(arr9)
print(arr9.shape)

print(arr9.squeeze())

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[0 1 2 3 4 5 6 7 8 9]


## 전치 행렬(transpose), T

In [193]:
arr10 = np.arange(15).reshape(3, 5)
arr10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [200]:
# 이미 생성된 행열이 생성 된 후에 트랜스를 하는 결과와 바로 행열을 맞춰서 만들 때 들어가는 값이 달라짐
print(arr10.transpose())

print()

arr10 = np.arange(15).reshape(5, 3)
print(arr10)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [211]:
arr2 = np.arange(12).reshape(2,6)
print(arr2.T)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [205]:
print(arr2.flatten())

[0 1 2 3 4 5 6 7 8 9]


## array간의 연산

In [209]:
# 리스트 간의 연결
arr1 = np.arange(15).reshape(3, 5)
arr1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [212]:
arr1 + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [213]:
arr1 + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [214]:
arr1 + [[[10]]]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

## 브로드캐스팅
- 다른 크기의 배열들 간에도 자동으로 연산해주는 Numpy의 강력한 기능

## 브로드캐스팅의 특징
    - 기본적으로는 shape와 같은 두 ndarray에 대한 연산은 각 원소별로 진행한다
    - 다른 shape를 갖는 array 간의 연산의 경우 브로드 캐스팅(shape를 맞춤) 후 진행한다

<img width=500 src='https://www.astroml.org/_images/fig_broadcast_visual_1.png' />

In [215]:
arr1 = np.arange(12).reshape(4, 3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [220]:
arr2 = np.arange(3)
arr1 + arr2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

## 브로드 캐스팅의 규칙
1. 뒷 차원부터 비교한다.
2. shape가 같아야 한다.
3. 차원 중 값이 1이 존재해야 한다.
4. [브로드캐스팅 공식문서](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [ ]:
"""
    차원에 1이 존재하는 경우 계산 가능
    6, 1, 5
       7, 3
          =
    6, 7, 5
"""

None

In [227]:
arr1 = np.arange(100, 104)
arr1

array([100, 101, 102, 103])

In [223]:
arr2 = np.arange(12).reshape(4, 3)
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [232]:
arr1 + arr2

SyntaxError: invalid syntax (4144468537.py, line 1)

<img src="https://numpy.org/doc/stable/_images/broadcasting_3.png" />

In [242]:
arr3 = np.arange(6).reshape(2, 3)
arr4 = np.arange(100, 106).reshape(3, 2)
print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[100 101]
 [102 103]
 [104 105]]


In [245]:
arr3.T + arr4

array([[100, 104],
       [103, 107],
       [106, 110]])

## 차원축(axis)
- 1차원 array라면 각 차원에 대한 axis = 0
- 2차원 array라면 각 차원에 대한 axis = 0, 1
- 3차원 array라면 각 차원에 대한 axis = 0, 1, 2

In [247]:
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [248]:
np.sum(arr1)

105

In [249]:
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [254]:
print(np.sum(arr1, axis=0))
print(np.sum(arr1, axis=1))

[15 18 21 24 27]
[10 35 60]


In [255]:
arr2 = np.arange(24).reshape(2, 3, 4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [262]:
print(np.sum(arr2, axis=0), end="\n\n")
print(np.sum(arr2, axis=1), end="\n\n")
print(np.sum(arr2, axis=2), end="\n\n")
print(np.sum(arr2, axis=-1), end="\n\n")

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[[ 6 22 38]
 [54 70 86]]

[[ 6 22 38]
 [54 70 86]]



## ★★★argmax() 자주쓰는 문법
- 최대값의 인덱스

In [267]:
arr3 = np.arange(5, 10)
print(arr3)
print(arr3.argmax())
print(arr3[arr3.argmax()])

[5 6 7 8 9]
4
9


In [282]:
np.random.seed(918)

arr4 = np.random.randint(10, size=(1, 6)).flatten()
print(arr4)
print(arr4.argmax())
print(arr4.argmin())
print(arr4.max())
print(arr4.min())

[9 3 3 4 2 5]
0
4
9
2


In [302]:
arr5 = np.random.randint(10, size=(3, 6))
print(arr5, end="\n\n")
print(arr5.argmax(axis=0), end="\n\n")
print(arr5.argmax(axis=1), end="\n\n")
print(arr5.max(axis=0), end="\n\n")
print(arr5.min(axis=1), end="\n\n")

[[8 8 1 6 1 5]
 [2 2 6 8 4 7]
 [4 0 1 3 2 6]]

[0 0 1 1 1 1]

[0 3 5]

[8 8 6 8 4 7]

[1 2 0]



## boolean selection, boolean indexing
- array 인덱싱 시, bool 타입의 조건에 맞는 list를 전달하여 조건식을 만족하는 True의 결과물만 필터링한다.

In [305]:
arr4 =  np.random.randint(1, 101, size=20)
print(arr4)

[73 33 77 19  5 21  5 35 91 46 96 83  7  2  6 22 79 92 62 38]


In [309]:
even_mask = arr4 % 2 == 0
arr4[even_mask]

array([46, 96,  2,  6, 22, 92, 62, 38])

## 다중 조건식
- & : and 조건식
- | : or 조건식

In [313]:
# 홀수이면서 50보다 작은 값
# and 조건 필요
np.random.seed(2026)

arr5 = np.random.randint(100, size=15)
print(arr5)

is_bound = (arr5 % 2 != 0) & (arr5 < 50)
print(arr5[is_bound])

print(arr5[is_bound].astype(str))

[ 1  6 26 56 77 77 29 28 51 69 76 28  2 54 77]
[ 1 29]
['1' '29']
